#!/bin/sh

echo "# Parts Gallery"
echo
for file in *.png; do
    if [ "$file" = "gallery.png" ]; then
        continue
    fi
    module="$(echo ${file} | sed 's/\.png//')"
    echo "![${module}](${file} \"${module}\")"
done
